name: Android CI

on:
  push:
      branches: [ master, xulongnr-patch-1 ]
      tags: []
#       paths:
#         - 'app/src/*'

  schedule:
      - cron: 0 0 * * 5 # Every Friday

#  pull_request:
#    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodule
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Download Go Libs
      run: curl -L https://github.com/trojan-gfw/igniter-go-libs/releases/download/1.6/golibs.aar > app/src/libs/golibs.aar

    - name: docker
      run: |
         sudo chown -R 3434:3434 .
         docker run --rm -v ${PWD}:/home/circleci/src circleci/android:api-28-ndk bash -c "
            #cd /opt/android;
            #sudo curl -O https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip;
            #sudo unzip android-ndk-r21-linux-x86_64.zip;
            #export ANDROID_NDK_HOME=/opt/android/android-ndk-r21;
            unset ANDROID_NDK_HOME;
            cd /home/circleci/src;
            ./gradlew assembleDebug;
            ./gradlew assembleRelease"
         ls -l build/app/build/outputs/apk/{debug,release}
         ls -l /opt/android/sdk/ndk

#    - name: Build with Gradle
#      run: ./gradlew assembleRelease
